#!/bin/bash
set -eu

CONFIG_DIR="${HOME}/.jouyuu"
if ! [ -d "${CONFIG_DIR}" ] ; then
  echo "Not found: ${CONFIG_DIR}"
  exit 1
fi
. "${CONFIG_DIR}/config"

EXCLUDE_FILE="${CONFIG_DIR}/exclude"
if ! [ -f "${EXCLUDE_FILE}" ] ; then
  echo "Not found: ${EXCLUDE_FILE}"
  exit 1
fi

LOG_FILE="${CONFIG_DIR}/bu-${JOUYUU_TO_TAG}.log"

set +e # Can not find an alt for $?
ssh "${JOUYUU_SERVER}" \
 "touch ${JOUYUU_SERVER_LOG_FILE} ; echo \"time=\$(date +%s) starting...\" >> ${JOUYUU_SERVER_LOG_FILE}"
/usr/bin/rsync -e ssh -rt --partial --verbose \
 --links --delete --delete-after \
 --log-file="${LOG_FILE}" \
 --exclude-from="${EXCLUDE_FILE}" \
 "${HOME}" "${JOUYUU_SERVER}:${JOUYUU_SERVER_PATH}/"
RES=$?
ssh "${JOUYUU_SERVER}" \
 "echo \"time=\$(date +%s) rsync=${RES}\" >> ${JOUYUU_SERVER_LOG_FILE}"

